// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDJ0W8QvTuK0NGDldF4iCtFrU_4uF4WWH4',
    appId: '1:479116966697:web:30d913be02ec2c3012d538',
    messagingSenderId: '479116966697',
    projectId: 'sign-in-and-register-c9bae',
    authDomain: 'sign-in-and-register-c9bae.firebaseapp.com',
    storageBucket: 'sign-in-and-register-c9bae.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAOn3dNUUCz8Qw69jYqtXuS90GqcT0KHk0',
    appId: '1:479116966697:android:30168b67b4b79b3212d538',
    messagingSenderId: '479116966697',
    projectId: 'sign-in-and-register-c9bae',
    storageBucket: 'sign-in-and-register-c9bae.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD9hOlMI1ZYZkAJyICgGcjrLJVcznXDy7E',
    appId: '1:479116966697:ios:59ca4a3508fca80d12d538',
    messagingSenderId: '479116966697',
    projectId: 'sign-in-and-register-c9bae',
    storageBucket: 'sign-in-and-register-c9bae.appspot.com',
    iosClientId: '479116966697-k4eq41sb4sb4oftgdl292s1f58og28o6.apps.googleusercontent.com',
    iosBundleId: 'com.example.signInAndRegister',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD9hOlMI1ZYZkAJyICgGcjrLJVcznXDy7E',
    appId: '1:479116966697:ios:59ca4a3508fca80d12d538',
    messagingSenderId: '479116966697',
    projectId: 'sign-in-and-register-c9bae',
    storageBucket: 'sign-in-and-register-c9bae.appspot.com',
    iosClientId: '479116966697-k4eq41sb4sb4oftgdl292s1f58og28o6.apps.googleusercontent.com',
    iosBundleId: 'com.example.signInAndRegister',
  );
}
